version: "3"

services:
  prometheus:
    container_name: prometheus-test
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    ports:
      - 8390:9090
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    extra_hosts:
      - "host.docker.internal:host-gateway"
  infludb:
    container_name: influxdb-test
    image: influxdb:2.0.7
    ports:
      - 8386:8086
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    container_name: grafana-test
    image: grafana/grafana
    restart: always
    ports:
      - 8383:3000
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    
volumes:
  grafana-data:
  prometheus_data: