version: "3"

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 8032:5432
    environment:
      POSTGRES_PASSWORD: 'RussianMunchkin'
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/database.sql:/app/database.sql
      - ./postgresql/database.sql:/docker-entrypoint-initdb.d/database.sql
      
volumes:
  grafana-data:
  prometheus_data: