global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: "server"
    scrape_interval: 1s # poll very quickly for a more responsive demo
    static_configs:
      - targets: ['host.docker.internal:8380']